# Generated by Django 4.1.6 on 2023-05-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("airport_name", models.CharField(max_length=100)),
                (
                    "airport_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
