# Generated by Django 4.1.6 on 2023-05-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rairline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "flight_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("capacity", models.PositiveSmallIntegerField()),
                ("duration", models.PositiveSmallIntegerField()),
                ("time", models.PositiveSmallIntegerField()),
                ("business", models.BooleanField()),
                ("eco_price", models.FloatField()),
                ("bus_price", models.FloatField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrivals",
                        to="rairline.airport",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departures",
                        to="rairline.airport",
                    ),
                ),
            ],
        ),
    ]
