# Generated by Django 4.1.6 on 2023-05-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rairline", "0002_flight"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                (
                    "pp_id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("url", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
