# Generated by Django 4.1.6 on 2023-05-15 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rairline", "0003_paymentprovider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "passenger_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("legal_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("date_of_birth", models.DateField()),
                ("passport_no", models.CharField(max_length=9, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact_no", models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "booking_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("date_of_departure", models.DateField()),
                (
                    "booking_class",
                    models.CharField(
                        choices=[("eco", "Economy"), ("bus", "Business")], max_length=3
                    ),
                ),
                ("invoice_id", models.IntegerField(null=True)),
                ("payment_received", models.BooleanField(default=False)),
                (
                    "flight_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rairline.flight",
                    ),
                ),
                (
                    "passenger_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rairline.passenger",
                    ),
                ),
                (
                    "payment_provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rairline.paymentprovider",
                    ),
                ),
            ],
        ),
    ]
